.catalog:
  name: "pgadmin4"
  version: "v0.0.1-rancher1"
  description: "Postgres web admin"
  minimum_rancher_version: v0.44.0
  questions:

    - variable: "SERVER_MODE"
      label: "Server mode"
      description: "Enable or not server mode"
      type: "enum"
      required: true
      default: yes
      options:
        - no
        - yes

    - variable: "SERVER_PORT"
      label: "Server port"
      description: "The port where the service listen for connection"
      type: "int"
      required: true
      default: 5999

    - variable: "STORAGE_MOUNT"
      description: "Local server path to be used to keep data"
      label: "Storage path"
      type: "string"
      required: true
      default: "/docker_data/pgadmin"

    - variable: "MAIL_SERVER"
      label: "Mail server address"
      description: "Mail server address to send email notification"
      type: "string"
      default: "mail.example.tld"
      required: false

    - variable: "MAIL_PORT"
      label: "Mail server port"
      description: "Mail server port"
      type: "int"
      default: 465
      required: false

    - variable: "MAIL_USE_SSL"
      label: "Mail server SSL"
      description: "Mail server require SSL"
      type: "string"
      default: "True"
      required: false

    - variable: "MAIL_USERNAME"
      label: "Mail server username"
      description: "Username to authenticate over mail server"
      type: "string"
      default: "user"
      required: false

    - variable: "MAIL_PASSWORD"
      label: "Mail server password"
      description: "Password to authenticate over mail server"
      type: "string"
      default: "password"
      required: false

pgadmin4:
  health_check:
    port: "${SERVER_PORT}"
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000